### ISSUE TITLE
activities checklist

### ISSUE THREAD

**Issue by Manikia** [Manikia/weatherApp#1]
- [ ] create city weather component that shows hard-coded information
- [ ] using app component state, add cities and render a city weather component for each
- [ ] create add city form component to add city to app component state so users can add cities to page
